from .calibration import PITCH_LANDMARKS_M, PitchCalibrator
from .compactness import (
    compute_centroid_separation,
    compute_frame_compactness,
    compute_team_compactness,
)
from .config import (
    PITCH_LENGTH_M,
    PITCH_WIDTH_M,
    SPORTS_BALL_CLASS_ID,
    SPORTS_DETECTION_CLASSES,
    SPORTS_GOALKEEPER_CLASS_ID,
    SPORTS_PLAYER_CLASS_ID,
    SPORTS_REFEREE_CLASS_ID,
    DriveConfig,
)
from .convex_hull import (
    compute_combined_convex_hull,
    compute_frame_convex_hull,
    compute_team_convex_hull,
    convex_hull_polygon,
    plot_convex_hull,
    save_convex_hull_frames,
)
from .detection import Detection, PlayerBallDetector, download_player_detection_weights
from .evaluation import (
    box_iou,
    compute_calibration_holdout_error,
    compute_clustering_accuracy,
    compute_detection_metrics,
    diagnose_team_assignment,
    ground_truth_boxes_dataframe,
    predicted_boxes_dataframe,
)
from .pipeline import TrackingPipeline
from .pitch import draw_pitch, plot_positions
from .pitch_keypoints import (
    PitchKeypointDetector,
    download_pitch_keypoint_weights,
    pitch_keypoint_template,
)
from .set_pieces import (
    compute_formation_repeatability,
    compute_track_speeds,
    compute_transition_time,
    detect_restart_frame,
    detect_team_dynamic_frame,
    extract_static_formation,
    match_formations,
    pick_team_by_swatch_color,
    plot_formation_matching,
    plot_formations,
    plot_speed_smoothing_comparison,
    plot_team_speed_timeline,
)
from .team import (
    JerseySample,
    TeamClassifier,
    collect_jersey_colors,
    collect_jersey_samples,
    extract_jersey_color,
    plot_jersey_color_samples,
    resolve_goalkeeper_team_ids,
    resolve_track_team_ids,
)
from .tracking import PlayerTracker, TrackedObject
from .video_io import VideoFrames, list_videos, mount_drive
from .voronoi import (
    compute_space_control,
    pitch_voronoi_cells,
    plot_voronoi,
    save_voronoi_frames,
    team_space_control,
    voronoi_cell_areas,
)

__all__ = [
    "PitchCalibrator",
    "PITCH_LANDMARKS_M",
    "DriveConfig",
    "PITCH_LENGTH_M",
    "PITCH_WIDTH_M",
    "SPORTS_BALL_CLASS_ID",
    "SPORTS_GOALKEEPER_CLASS_ID",
    "SPORTS_PLAYER_CLASS_ID",
    "SPORTS_REFEREE_CLASS_ID",
    "SPORTS_DETECTION_CLASSES",
    "Detection",
    "PlayerBallDetector",
    "download_player_detection_weights",
    "TrackingPipeline",
    "box_iou",
    "predicted_boxes_dataframe",
    "ground_truth_boxes_dataframe",
    "compute_detection_metrics",
    "compute_calibration_holdout_error",
    "compute_clustering_accuracy",
    "diagnose_team_assignment",
    "draw_pitch",
    "plot_positions",
    "PitchKeypointDetector",
    "download_pitch_keypoint_weights",
    "pitch_keypoint_template",
    "TeamClassifier",
    "JerseySample",
    "collect_jersey_colors",
    "collect_jersey_samples",
    "extract_jersey_color",
    "plot_jersey_color_samples",
    "resolve_track_team_ids",
    "resolve_goalkeeper_team_ids",
    "PlayerTracker",
    "TrackedObject",
    "VideoFrames",
    "list_videos",
    "mount_drive",
    "compute_frame_compactness",
    "compute_team_compactness",
    "compute_centroid_separation",
    "pitch_voronoi_cells",
    "voronoi_cell_areas",
    "team_space_control",
    "compute_space_control",
    "plot_voronoi",
    "save_voronoi_frames",
    "convex_hull_polygon",
    "compute_frame_convex_hull",
    "compute_team_convex_hull",
    "compute_combined_convex_hull",
    "plot_convex_hull",
    "save_convex_hull_frames",
    "compute_track_speeds",
    "detect_restart_frame",
    "detect_team_dynamic_frame",
    "compute_transition_time",
    "extract_static_formation",
    "match_formations",
    "compute_formation_repeatability",
    "pick_team_by_swatch_color",
    "plot_formations",
    "plot_formation_matching",
    "plot_team_speed_timeline",
    "plot_speed_smoothing_comparison",
]
